### ISSUE TITLE
Error when getting invoices.

### ISSUE THREAD

**Issue by JestinHoogeveen** [Vleks/bol-plaza-sdk#1]
Hello,

I'm trying to get my invoices but I receive an error: ` <?xml version="1.0" encoding="UTF-8" standalone="yes"?><ServiceError xmlns="https://plazaapi.bol.com/services/xsd/v2/plazaapi.xsd"><errorCode>404</errorCode><errorMessage>Not Found</errorMessage></ServiceError>`

What could be the problem and how can I solve it?

**Comment by mikemadern** [comment]
Hi Justin,

Did you try to receive all your invoices `$client->getInvoices($period);`, or a single invoice `$client->getInvoice($invoiceId);`?

**Comment by JestinHoogeveen** [comment]
I'm receiving it when using getInvoices().

**Comment by mikemadern** [comment]
Hi Jestin,

Do you get the same results when using the following code?

```
try {
    $period    = '';
    $result    = $client->getInvoices($period);

    printf('<pre>%s</pre>', print_r($result, true));
} catch (ClientException $clientException) {
    printf('<pre>%s</pre>', print_r($clientException, true));
} catch (EntityException $entityException) {
    printf('<pre>%s</pre>', print_r($entityException, true));
} catch (InvalidArgumentException $invalidArgumentException) {
    printf('<pre>%s</pre>', print_r($invalidArgumentException, true));
}
```

When you do not, could you provide the code snippet you used?

**Comment by JestinHoogeveen** [comment]
Yes, I tried this code:

'
        $publicKey = '***';
        $privateKey = '***';


        require DIR_VENDOR . 'autoload.php';

        $bolPlazaClient = new Client($publicKey, $privateKey);
        $bolPlazaClient->setTestMode(true);

        try {
            $period    = '2017-01-01/2017-02-01';
            $result    = $bolPlazaClient->getInvoices($period);
            printf('<pre>%s</pre>', print_r($result, true));
        } catch (ClientException $clientException) {
            printf('<pre>%s</pre>', print_r($clientException, true));
        } catch (EntityException $entityException) {
            printf('<pre>%s</pre>', print_r($entityException, true));
        } catch (InvalidArgumentException $invalidArgumentException) {
            printf('<pre>%s</pre>', print_r($invalidArgumentException,
true));
        }


   '

**Comment by mikemadern** [comment]
Hi Jestin,

You've set TestMode to `true`, while not documented, invoices can't be fetched in test mode.
Try receiving your invoices with the production keys.
