### ISSUE TITLE
paging didn't work?

### ISSUE THREAD

**Issue by yassirAwad** [Vleks/bol-plaza-sdk#2]
i have this code:
` private $client;

    function __construct()
    {
        $this->client = new Client(env("BOL_PUBLIC_KEY"), env("BOK_PRIVATE_KEY"));
        $this->client->setTestMode(false);
    }

    public function getOrders()
    {
        try {
            $orders = $this->client->getOrders(5);
        } catch (ClientException $clientException) {
            echo 'An error occurred: ' . $clientException->getMessage();
        }
    }`

why when i using paging in  function `getOrders` its not works?
the values returned in response of page 5 or any other pages is the same of values of page 1

**Comment by mikemadern** [comment]
Thank you for your bug report.
We just released version 1.1.1 which contains a resolution that solves the problems you experienced.
