### ISSUE TITLE
getOrders

### ISSUE THREAD

**Issue by webvoicenl** [Vleks/bol-plaza-sdk#3]
Beste ontwikkelaar,

De meeste functies werken naar behoren. Echter krijg ik de getOrders functie niet aan de gang.
Wat heb ik geprobeerd:
$client->getOrders(1, 'FBB');
$client->getOrders(1, 'FBR');
$client->getOrders(1);
$client->getOrders();
Dit is de return.
```
Vleks\BolPlazaSDK\Results\OrderList Object
(
    [fields:protected] => Array
        (
            [Order] => Array
                (
                    [value] => Array
                        (
                        )

                    [type] => Array
                        (
                            [0] => Vleks\BolPlazaSDK\Results\Order
                        )

                )

        )

    [name:protected] => 
)
```

Daarnaast krijg ik voor elke getInvoices() altijd dezelfde InvoiceId terug en het zelfde bedrag, ook al voer ik een andere periode in.

Ben erg benieuwd naar jullie reactie.

Mvg,
Martijn

**Comment by mikemadern** [comment]
Hoi Martijn,

De return die je krijgt vanuit `getOrders` geeft aan dat er geen orders zijn om op te halen.
In tests die ik heb uitgevoerd over onze accounts ben ik geen vreemde zaken tegen gekomen.

Ook `getInvoices` werken bij deze accounts i.c.m. verschillende perioden.

Wanneer je nog geen gebruik maakt van versie `1.1.1` wil ik je vragen te updaten om zo te kijken of daarmee de problemen zijn opgelost.

**Comment by webvoicenl** [comment]
Hey Mike,

Bedankt voor je reactie.
Als ik de documentatie goed interpreteer gaat het alleen om openstaande orders? Het is dus niet mogelijk om alle LVB orders van een bepaalde periode op te halen?

In mijn composer.lock bestand staat versie 1.1.1 dat moet dus goed staan.

Als ik de invoices wil ophalen door middel van de examples/invoices.php code
```
$period    = '2018-06-01/2018-06-15';
$period    = '2018-06-01/2018-06-15';
$period    = '2018-05-01/2018-06-01';
$period    = '';
```

krijg altijd invoice ID: 2147483647 terug

als ik vervolgens de invoice wil ophalen met 
$client->getInvoice(2147483647);

krijg ik de volgende error.

`Fatal error: Uncaught exception 'Vleks\BolPlazaSDK\Exceptions\ServiceException' with message 'The requested resource could not be retrieved. Error ID: 1wzr4ojiydw76p' in C:\xampp\htdocs\lvb-api\vendor\vleks\bol-plaza-sdk\src\Client.php:552 Stack trace: #0 C:\xampp\htdocs\lvb-api\vendor\vleks\bol-plaza-sdk\src\Client.php(480): Vleks\BolPlazaSDK\Client->checkResponse(Resource id #8, Array, 'The requested r...') #1 C:\xampp\htdocs\lvb-api\vendor\vleks\bol-plaza-sdk\src\Client.php(367): Vleks\BolPlazaSDK\Client->request('GET', '/services/rest/...', NULL, Array) #2 C:\xampp\htdocs\lvb-api\vendor\vleks\bol-plaza-sdk\examples\invoices.php(63): Vleks\BolPlazaSDK\Client->getInvoice('2147483647') #3 {main} thrown in C:\xampp\htdocs\lvb-api\vendor\vleks\bol-plaza-sdk\src\Client.php on line 552`

Heel bijzonder dat het bij jullie wel werkt. Ik heb de sdk geinstalleerd via 
`composer require vleks/bol-plaza-sdk`

En ik gebruik de api keys voor productie. Inventory ophalen werkt bijvoorbeeld perfect!

Als ik testmode op true zet en test keys gebruik krijg ik de volgende melding:
`Fatal error: Uncaught exception 'Vleks\BolPlazaSDK\Exceptions\ServiceException' with message '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><ServiceError xmlns="https://plazaapi.bol.com/services/xsd/v2/plazaapi.xsd"><errorCode>404</errorCode><errorMessage>Not Found</errorMessage></ServiceError>' in C:\xampp\htdocs\lvb-api\vendor\vleks\bol-plaza-sdk\src\Client.php:552 Stack trace: #0 C:\xampp\htdocs\lvb-api\vendor\vleks\bol-plaza-sdk\src\Client.php(480): Vleks\BolPlazaSDK\Client->checkResponse(Resource id #8, Array, '<?xml version="...') #1 C:\xampp\htdocs\lvb-api\vendor\vleks\bol-plaza-sdk\src\Client.php(352): Vleks\BolPlazaSDK\Client->request('GET', '/services/rest/...', Array, Array) #2 C:\xampp\htdocs\lvb-api\vendor\vleks\bol-plaza-sdk\examples\invoices.php(46): Vleks\BolPlazaSDK\Client->getInvoices('2018-06-01/2018...') #3 {main} thrown in C:\xampp\htdocs\lvb-api\vendor\vleks\bol-plaza-sdk\src\Client.php on line 552`

**Comment by webvoicenl** [comment]
Ik heb even gewacht totdat er een LVB order open stond. Zodra ik dan getOrdes ophaal krijg ik niks terug.
`object(Vleks\BolPlazaSDK\Results\OrderList)#38 (2) { ["fields":protected]=> array(1) { ["Order"]=> array(2) { ["value"]=> array(0) { } ["type"]=> array(1) { [0]=> string(31) "Vleks\BolPlazaSDK\Results\Order" } } } ["name":protected]=> NULL }`

**Comment by webvoicenl** [comment]
Beste Mike,

Ik denk dat ik het probleem heb gevonden. ik kan de invoices ophalen door de betreffende periode in te vullen via getInvoices(). Echter ontvang ik altijd **dezelfde orderId**. Het orderId is altijd: 2147483647

Dit id is ook de hoogst mogelijke waarde van een int32... 

Hierdoor kan ik het juiste invoideId niet uitlezen en ophalen.

**Comment by mikemadern** [comment]
Hoi Martijn,

Bedankt voor je onderzoek en je oplossing!
We zullen deze aanpassingen overnemen in onze volgende release van de SDK.
